(() => {
const { addCard, deleteCards, getDeckById, updateCard } = window.RecallDeckStorage;
const $ = (s) => document.querySelector(s);
const deckId = new URLSearchParams(location.search).get('deck');
let deck = deckId ? getDeckById(deckId) : null;
let cards = deck?.cards ?? [], index = 0, editingId = null;
const card = $('#learning-card'), answer = $('#learning-answer'), reveal = $('#study-reveal-button');
const previous = $('#previous-card'), next = $('#next-card'), add = $('#add-card-button'), edit = $('#edit-card-button'), remove = $('#delete-card-button');
const addDialog = $('#add-card-dialog'), editListDialog = $('#edit-card-list-dialog'), editDialog = $('#edit-card-dialog'), deleteDialog = $('#delete-card-dialog');
const addForm = $('#add-card-form'), editForm = $('#edit-card-form');
const fields = ['word', 'reading', 'type', 'meaning', 'example', 'translation'];
function refresh() { deck = getDeckById(deckId); cards = deck?.cards ?? []; }
function close(dialog) { if (dialog.open) dialog.close(); }
function formValues(form) { const data = new FormData(form); return Object.fromEntries(fields.map((field) => [field, String(data.get(field)).trim()])); }
function hideAnswer() { card.classList.remove('revealed'); reveal.textContent = 'Reveal answer'; reveal.setAttribute('aria-expanded', 'false'); answer.setAttribute('aria-hidden', 'true'); }
function controls() { const empty = !cards.length, full = Number.isFinite(deck?.maxCards) && cards.length >= deck.maxCards; reveal.disabled = empty; previous.disabled = empty || index === 0; next.disabled = empty || index === cards.length - 1; edit.disabled = empty; remove.disabled = empty; add.disabled = full; add.textContent = full ? 'Card limit reached' : '+ Add a card'; $('#deck-card-count').textContent = Number.isFinite(deck?.maxCards) ? `${cards.length} of ${deck.maxCards} cards in deck` : `${cards.length} cards in deck`; }
function renderCard() {
  hideAnswer();
  if (!cards.length) { $('#card-word').textContent = 'No cards yet'; $('#card-reading').textContent = ''; $('#card-type').textContent = 'EMPTY DECK'; $('#card-meaning').textContent = 'Add a card to begin studying.'; $('#card-example').textContent = ''; $('#card-translation').textContent = ''; $('#card-count').textContent = '00 / 00'; $('#progress-text').textContent = 'No cards in deck'; $('#progress-percent').textContent = '0%'; $('#progress-bar').style.width = '0%'; controls(); return; }
  index = Math.min(index, cards.length - 1); const current = cards[index], position = index + 1, percent = Math.round(position / cards.length * 100);
  fields.forEach((field) => { const target = $(`#card-${field}`); if (target) target.textContent = current[field]; });
  $('#card-count').textContent = `${String(position).padStart(2, '0')} / ${String(cards.length).padStart(2, '0')}`; $('#progress-text').textContent = `Card ${position} of ${cards.length}`; $('#progress-percent').textContent = `${percent}%`; $('#progress-bar').style.width = `${percent}%`; controls();
}
function renderDeck() { if (!deck) { $('#study-content').hidden = true; $('#deck-not-found').hidden = false; return; } document.title = `${deck.title} — Recall`; $('meta[name="description"]').content = deck.description; $('#deck-label').textContent = `${deck.language} · ${deck.level}`; $('#deck-title').textContent = deck.title; $('#deck-title-accent').textContent = ''; $('#deck-description').textContent = deck.description; $('#card-language').textContent = deck.language; $('#card-level').textContent = deck.level; $('#card-prompt').textContent = deck.prompt; document.querySelectorAll('[data-dialog-deck-name]').forEach((node) => { node.textContent = deck.title; }); renderCard(); }
function toggle() { if (!cards.length) return; const shown = !card.classList.contains('revealed'); card.classList.toggle('revealed', shown); reveal.textContent = shown ? 'Hide answer' : 'Reveal answer'; reveal.setAttribute('aria-expanded', String(shown)); answer.setAttribute('aria-hidden', String(!shown)); }
function move(amount) { if (!cards.length) return; const target = index + amount; if (target < 0 || target >= cards.length) return; index = target; renderCard(); }
function openAdd() { if (!deck || add.disabled) return; addForm.reset(); $('#add-card-message').textContent = ''; $('#deck-capacity-message').textContent = Number.isFinite(deck.maxCards) ? `Complete every field. This deck can contain up to ${deck.maxCards} cards.` : 'Complete every field.'; addDialog.showModal(); addForm.elements.word.focus(); }
function saveAdd(event) { event.preventDefault(); const values = formValues(addForm); if (Object.values(values).some((value) => !value)) { $('#add-card-message').textContent = 'Please complete every field.'; return; } if (Number.isFinite(deck.maxCards) && cards.length >= deck.maxCards) return; addCard(deckId, { ...values, type: values.type.toUpperCase() }); refresh(); index = cards.length - 1; close(addDialog); renderCard(); }
function renderEditList() { const list = $('#edit-card-list'); list.replaceChildren(); cards.forEach((item) => { const row = document.createElement('article'); row.className = 'edit-card-option'; const summary = document.createElement('div'); summary.className = 'edit-card-summary'; const word = document.createElement('strong'); word.textContent = item.word; const details = document.createElement('small'); details.textContent = `${item.reading} · ${item.type}`; const meaning = document.createElement('p'); meaning.textContent = `${item.meaning} — ${item.example} / ${item.translation}`; summary.append(word, document.createElement('br'), details, meaning); const button = document.createElement('button'); button.type = 'button'; button.className = 'edit-one-card-button'; button.dataset.cardId = item.id; button.textContent = 'Edit'; button.setAttribute('aria-label', `Edit ${item.word}`); row.append(summary, button); list.append(row); }); }
function openEditList() { if (!cards.length) return; renderEditList(); editListDialog.showModal(); }
function openEdit(id) { const item = cards.find((candidate) => candidate.id === id); if (!item) return; editingId = id; fields.forEach((field) => { editForm.elements[field].value = item[field]; }); $('#edit-card-message').textContent = ''; close(editListDialog); editDialog.showModal(); editForm.elements.word.focus(); }
function saveEdit(event) { event.preventDefault(); if (!editingId) return; const values = formValues(editForm); if (Object.values(values).some((value) => !value)) { $('#edit-card-message').textContent = 'Please complete every field.'; return; } updateCard(deckId, editingId, { ...values, type: values.type.toUpperCase() }); refresh(); index = Math.max(0, cards.findIndex((item) => item.id === editingId)); editingId = null; close(editDialog); renderCard(); }
function selectedIds() { return [...$('#delete-card-list').querySelectorAll('input:checked')].map((input) => input.value); }
function updateSelection() { const count = selectedIds().length; $('#selected-card-count').textContent = `${count} ${count === 1 ? 'card' : 'cards'} selected`; $('#confirm-delete-button').disabled = !count; $('#select-all-cards').checked = cards.length > 0 && count === cards.length; $('#select-all-cards').indeterminate = count > 0 && count < cards.length; }
function openDelete() { if (!cards.length) return; const list = $('#delete-card-list'); list.replaceChildren(); cards.forEach((item) => { const label = document.createElement('label'); label.className = 'delete-card-option'; const input = document.createElement('input'); input.type = 'checkbox'; input.name = 'cards-to-delete'; input.value = item.id; const identity = document.createElement('span'); const word = document.createElement('strong'); word.textContent = item.word; const details = document.createElement('small'); details.textContent = `${item.reading} · ${item.type}`; identity.append(word, document.createElement('br'), details); const meaning = document.createElement('span'); meaning.className = 'card-list-meaning'; meaning.textContent = item.meaning; label.append(input, identity, meaning); list.append(label); }); $('#delete-card-message').textContent = ''; updateSelection(); deleteDialog.showModal(); }
function deleteSelected(event) { event.preventDefault(); const ids = selectedIds(); if (!ids.length) return; deleteCards(deckId, ids); refresh(); index = Math.min(index, Math.max(cards.length - 1, 0)); close(deleteDialog); renderCard(); }
reveal.addEventListener('click', toggle); previous.addEventListener('click', () => move(-1)); next.addEventListener('click', () => move(1)); add.addEventListener('click', openAdd); addForm.addEventListener('submit', saveAdd); edit.addEventListener('click', openEditList); editForm.addEventListener('submit', saveEdit); remove.addEventListener('click', openDelete); $('#delete-card-form').addEventListener('submit', deleteSelected);
$('#edit-card-list').addEventListener('click', (event) => { const button = event.target.closest('.edit-one-card-button'); if (button) openEdit(button.dataset.cardId); }); $('#delete-card-list').addEventListener('change', updateSelection); $('#select-all-cards').addEventListener('change', (event) => { $('#delete-card-list').querySelectorAll('input').forEach((input) => { input.checked = event.target.checked; }); updateSelection(); });
[['#close-add-card',addDialog],['#close-edit-card-list',editListDialog],['#close-edit-card',editDialog],['#close-delete-card',deleteDialog]].forEach(([selector, dialog]) => $(selector).addEventListener('click', () => close(dialog))); $('#back-to-edit-list').addEventListener('click', () => { close(editDialog); editingId = null; openEditList(); }); [addDialog, editListDialog, editDialog, deleteDialog].forEach((dialog) => dialog.addEventListener('click', (event) => { if (event.target === dialog) close(dialog); }));
document.addEventListener('keydown', (event) => { const blocked = document.activeElement?.matches('input, textarea, select, button, [contenteditable="true"]') || $('dialog[open]'); if (blocked) return; if (event.key === ' ') { if (!cards.length) return; event.preventDefault(); toggle(); } else if (event.key === 'ArrowLeft') move(-1); else if (event.key === 'ArrowRight') move(1); });
renderDeck();
})();
